server:
    port: 8080


spring:
    application:
      name: holding-provider


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:9091/eureka/}
  instance:
    preferIpAddress: true